services:

  otelcollector:
    container_name: otelcollector
    image: otel/opentelemetry-collector-contrib:latest
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./configs/otel-collector.yml:/etc/otel-collector.yml:ro
    command:
      - --config=/etc/otel-collector.yml
    restart: on-failure
    networks:
      - monitoring
    labels:
      - logging=promtail

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring
    volumes:
      - ./configs/alert-rules.yml:/etc/prometheus/alert-rules.yml
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: on-failure
    labels:
      - logging=promtail

  blackbox:
    container_name: blackbox
    image: prom/blackbox-exporter:latest
    volumes:
      - ./configs/blackbox.yml:/etc/blackbox-exporter/blackbox.yml
    ports:
      - "9115:9115"
    networks:
      - monitoring
    labels:
      - logging=promtail

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "0"
    volumes:
      - ./configs/datasource.yml:/etc/grafana/provisioning/datasource/provisioning-datasource.yml:ro
      - ./configs/grafana:/var/lib/grafana

    environment:
      #- GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_PASSWORD=admin
      #- GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_USERS_DEFAULT_THEME=light
      - GF_SERVER_ROOT_URL=http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - tempo
      - loki
    networks:
      - monitoring
    labels:
      - logging=promtail

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - 3100:3100
    volumes:
      - ./configs/loki-config.yml:/etc/loki/loki-config.yml
    networks:
      - monitoring
    restart: on-failure
    labels:
      - logging=promtail

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./configs/var/log:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
    command:
      - --config.file=/etc/promtail/promtail-config.yml
    restart: on-failure
    networks:
      - monitoring
    labels:
      - logging=promtail

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    volumes:
      - ./configs/tempo-local.yml:/etc/tempo-local.yml
     # - /mnt/volumes/observabilidade/prod/tempo:/tempo
    ports:
      - 3200:3200
    command:
      - --config.file=/etc/tempo-local.yml
      - --target=all
      - --storage.trace.backend=local
      - --storage.trace.local.path=/var/tempo
      - --auth.enabled=false
    networks:
      - monitoring
    restart: on-failure
    labels:
      - logging=promtail

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./configs/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - monitoring
    restart: on-failure
    labels:
      - logging=promtail



#volumes:
#  db_mongo:
#  grafana_data:
networks:
  monitoring:
    driver: bridge
